<!-- View -->
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <!-- My CSS -->
    <link rel="stylesheet" href="/css/myStyle.css">

    <title><?php echo $view->pageTitle;?></title>
</head>
<body>

<div class="nav navbar">
    <a class="btn btn-primary" href="index.php">Home</a>
    <a class="btn btn-primary" href="search.php">Search</a>

    <!-- Shows login / register buttons if the user is logged out. -->
    <?php if (!isset($_SESSION["loggedin"]))
    {
        require "view/login.phtml";
        require "view/register.phtml";
    }
    else
    {
        echo "<a class='btn btn-primary' href='message.php'>Messages</a>";
        echo "<a class='btn btn-primary' href='account.php'>Account</a>";
        require "view/createPost.phtml";
        require "view/logout.phtml";
    }
    ?>

</div>


