<!-- View -->
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <!-- My CSS -->
    <link rel="stylesheet" href="/css/myStyle.css">

    <title><?php echo $view->pageTitle;?></title>
</head>
<body>

<div class="container nav">
    <div class="row">
        <div class="col-auto">
            <a href="index.php">Home</a>
        </div>
        <div class="col-auto">
            <a href="database.php">Database</a>
        </div>
        <div class="col-auto">
            <!-- Shows login button if the user is logged out. -->
            <?php if (!isset($_SESSION["loggedIn"])){
                echo <<< EOT
<!-- Button trigger modal -->
<button id="login" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Login
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Thanks for visiting. Enjoy your travels citizen. 
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary">Log In</button>
            </div>
        </div>
    </div>
</div>

<!-- Button trigger modal -->
<button id="login" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Register
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Thanks for visiting. Enjoy your travels citizen. 
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary">Log In</button>
            </div>
        </div>
    </div>
</div>

EOT;
            };
            ?>
        </div>
    </div>
</div>

