<!-- View -->
<!-- Button trigger modal -->
<button id="addWatch" type="button" class="btn btn-success" data-toggle="modal" data-target="#addWatchModal">
    Add to Watch List
</button>

<!-- Modal -->
<div class="modal fade" id="addWatchModal" tabindex="-1" role="dialog" aria-labelledby="addWatchModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addWatchModalLabel">Confirm add to watchlist</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Write your reply below.</p>

                <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">

                    <div class="form-group">
                        <label><?php echo $view->threadID;?></label>
                        <input type="text" name="postID" value="<?php echo $view->threadID;?>">
                    </div>

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" name="submit" value="subscribe">Subscribe</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
            </form>
        </div>
    </div>
</div>