<!-- View -->
<!-- Button trigger modal -->
<button id="newMessage" type="button" class="btn btn-success" data-toggle="modal" data-target="#newMessageModal">
    Create Message
</button>

<!-- Modal -->
<div class="modal fade" id="newMessageModal" tabindex="-1" role="dialog" aria-labelledby="newMessageModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newMessageModalLabel">Create Message</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Write your message below.</p>

                <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">

                    <div class="form-group">
                        <label>Title</label>
                        <input type="text" name="messageTitle" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label>Content</label>
                        <input type="text" name="messageContent" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <input hidden type="text" name="messageOwner" class="form-control" value="<?php echo $_SESSION['userID']?>">
                    </div>
                    <div class="form-group">
                        <input hidden type="text" name="messageRecip" class="form-control" value="<?php echo $view->user->getUserID();?>">
                    </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" name="submit" value="submitMessage">Submit</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
            </form>
        </div>
    </div>
</div>