<!-- View -->
<!-- Button trigger modal -->
<button id="reply" type="button" class="btn btn-success" data-toggle="modal" data-target="#replyModal">
    Create Reply
</button>

<!-- Modal -->
<div class="modal fade" id="replyModal" tabindex="-1" role="dialog" aria-labelledby="replyModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="replyModalLabel">Create Reply</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Write your reply below.</p>

                <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">

                    <div class="form-group">
                        <label>Content</label>
                        <input type="text" name="replyContent" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label><?php echo $view->threadID;?></label>
                        <input type="text" name="postID" value="<?php echo $view->threadID;?>">
                    </div>

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" name="submit" value="submitReply">Submit</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
            </form>
        </div>
    </div>
</div>

