<!-- View -->
<?php require ('view/template/header.phtml'); ?>

<div class="jumbotron">
    <h1>Database</h1>
</div>

<div class="shadow-lg">
    <div class=""></div>
</div>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <table class="datatable">
        <thead><tr> <th>Student ID</th> <th>First name</th> <th>Last name</th> <th>International</th> <th>CourseID</th> </tr></thead><tbody>
        <?php foreach ($view->studentsDataSet as $studentData) {
            echo '<tr> <td>' . $studentData->getStudentID() . '</td> <td>' . $studentData->getFirstName() . '</td> <td>' . $studentData->getLastName() . '</td> <td>' . $studentData->getInternational() . '</td> <td>' . $studentData->getCourseID() . '</td> </td> </tr>';} ?>
        </tbody></table>

<?php require ('view/template/footer.phtml'); ?>
