<!-- View -->

<?php require ('view/template/header.phtml'); ?>

<div class="jumbotron">
    <h1>Lets Talk: Star Citizen</h1>
</div>

<div class="">
    <h2>Latest Posts</h2>
</div>

<div class="row">
    <div class="col-auto">
        <div class="card" style="width: 18rem;">
            <!--<img src="..." class="card-img-top" alt="...">-->
            <div class="card-body">
                <h5 class="card-title">Watch List</h5>
                <?php foreach ($view->watchList as $watch)
                {
                    echo <<<EOT
    <p class="card-text"> {$watch->getPostTitle()}</p>
    <a href="viewPost.php?postID={$watch->getPostID()}" class="btn btn-primary">View Post</a>
EOT;
                } ?>
            </div>
        </div>
    </div>

    <?php foreach ($view->postHandler as $post)
    {
        echo <<<EOT
<div class="col-auto">
<div class="card" style="width: 18rem;">
    <!--<img src="..." class="card-img-top" alt="...">-->
    <div class="card-body">
    <h5 class="card-title"> {$post->getPostTitle()} </h5>
    <p class="card-text"> {$post->getPostOwner()} </p>
    <a href="viewPost.php?postID={$post->getPostID()}" class="btn btn-primary">View Post</a>
    </div>
</div>
</div>
EOT;
    } ?>
</div>

<div class="container-fluid">
    <div class="alert-warning">
        <p>This website uses cookies to enhance your browsing session.</p>
    </div>
</div>

<?php require ('view/template/footer.phtml'); ?>