<!-- View -->

<?php require ('view/template/header.phtml'); ?>

<div class="jumbotron">
    <h1>Lets Talk: Star Citizen</h1>
</div>

<div class="">
    <h2>Latest Posts</h2>
</div>

<div class="row">
<?php foreach ($view->postHandler as $post)
{
    echo <<<EOT
<div class="col-md-4">
<div class="card" style="width: 18rem;">
    <!--<img src="..." class="card-img-top" alt="...">-->
    <div class="card-body">
    <h5 class="card-title"> {$post->getPostTitle()} </h5>
    <p class="card-text"> {$post->getPostOwner()} </p>
    <a href="#" class="btn btn-primary">View Post</a>
    </div>
</div>
</div>
EOT;
} ?>
</div>

<?php require ('view/template/footer.phtml'); ?>