<!-- View -->
<!-- Button trigger modal -->
<button id="removeWatch" type="button" class="btn btn-success" data-toggle="modal" data-target="#removeWatchModal">
    Unsubscribe
</button>

<!-- Modal -->
<div class="modal fade" id="removeWatchModal" tabindex="-1" role="dialog" aria-labelledby="removeWatchModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="removeWatchModalLabel">Unsubscribe</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Confirm to unsubscribe.</p>

                <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">

                    <div class="form-group">
                        <input hidden type="text" name="postID" value="<?php echo $view->threadID;?>">
                    </div>

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" name="submit" value="unsubscribe">Unsubscribe</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
            </form>
        </div>
    </div>
</div>