<?php require_once('view/template/header.phtml');?>

<div class="container">
    <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">
        <div class="form-group">
            <input type="text" name="search" class="form-control">
            <button type="submit" class="btn btn-primary" name="submit" value="searchMessage">Search</button>
        </div>
    </form>
</div>

<div class="container">
    <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">
        <div class="form-group">
            <input type="text" name="searchUser" class="form-control">
            <button type="submit" class="btn btn-primary" name="submit" value="searchUser">User Search</button>
        </div>
    </form>
</div>

<div class="card-body">
    <?php if(isset($view->user))
    {
        echo $view->user->getUserName() . date('d-m-Y', strtotime($view->user->getDateJoined()));
    }?>

</div>


<?php require_once('view/template/footer.phtml');?>
<div class="container">
