<!-- View -->

<div class="container-fluid">
    <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">
        <div class="form-group">
            <input type="text" name="searchUser" class="form-control">
            <button type="submit" class="btn btn-primary" name="submit" value="searchUser">User Search</button>
        </div>
    </form>
</div>

<?php if(isset($view->user)) : ?>
<?php $date = date('d-m-Y', strtotime($view->user->getDateJoined()));?>
<div class="col-sm">
    <div class="card" style="width: 18rem;">
        <img src='images/user/<?=$view->user->getProfileImage()?>' class='card-img-top' alt=' '>
        <div class="card-body">
            <h5 class="card-title">Username: <?=$view->user->getUserName()?></h5>
            <p class="card-text">Date Joined: <?=$date?></p>
            <?php require_once('view/createMessage.phtml');?>
            <?php endif; ?>
        </div>
    </div>
</div>
