<div class="col-auto">
        <div class="card" style="width: 18rem;">
            <!--<img src="..." class="card-img-top" alt="...">-->
            <div class="card-body">
                <h5 class="card-title">Watch List</h5>
                <?php foreach ($view->watchList as $watch)
                {
                    echo <<<EOT
    <p class="card-text"> {$watch->getPostTitle()}</p>
    <a href="viewPost.php?postID={$watch->getPostID()}" class="btn btn-primary">View Post</a>
EOT;
                } ?>
            </div>
        </div>
    </div>

